{
  "name": "",
  "version": "0.1.0",
  "description": "",
  "license": "MIT",
  "keywords": [],
  "homepage": "https://github.com/entropy-tamer/mappy",
  "repository": {
    "type": "git",
    "url": "https://github.com/entropy-tamer/mappy.git"
  },
  "bugs": "https://github.com/entropy-tamer/mappy/issues",
  "dependencies": {},
  "devDependencies": {},
  "cargo": {
    "workspace": {
      "members": [
        "mappy-core",
        "mappy-client",
        "mappy-python",
        "mappy-server"
      ],
      "resolver": "2",
      "package": {
        "version": "0.1.0",
        "edition": "2024",
        "authors": [
          "Reynard Team"
        ],
        "license": "MIT",
        "repository": "https://github.com/entropy-tamer/mappy",
        "description": "Space-efficient maplet data structures for approximate key-value mappings"
      },
      "dependencies": {
        "tokio": {
          "version": "1.48.0",
          "features": [
            "full"
          ]
        },
        "async-trait": "0.1.89",
        "serde": {
          "version": "1.0.228",
          "features": [
            "derive"
          ]
        },
        "serde_json": "1.0.145",
        "bincode": "2.0.1",
        "ahash": "0.8.12",
        "bitvec": "1.0.1",
        "twox-hash": "2.1.2",
        "anyhow": "1.0.100",
        "thiserror": "2.0.17",
        "parking_lot": "0.12.5",
        "rayon": "1.11.0",
        "tracing": "0.1.41",
        "tracing-subscriber": {
          "version": "0.3.20",
          "features": [
            "env-filter"
          ]
        },
        "criterion": {
          "version": "0.7.0",
          "features": [
            "html_reports"
          ]
        },
        "proptest": "1.8.0",
        "quickcheck": "1.0.3",
        "pyo3": {
          "version": "0.27.1",
          "features": [
            "extension-module"
          ]
        },
        "getrandom": "0.3.4",
        "rand": "0.9.2",
        "rand_core": "0.9.3",
        "axum": {
          "version": "0.8.6",
          "features": [
            "macros"
          ]
        },
        "tower": "0.5.2",
        "tower-http": {
          "version": "0.6.6",
          "features": [
            "cors",
            "trace",
            "fs"
          ]
        },
        "hyper": {
          "version": "1.7.0",
          "features": [
            "full"
          ]
        },
        "tls": {
          "package": "tokio-rustls",
          "version": "0.26.4"
        },
        "config": "0.15.18",
        "dotenvy": "0.15.7"
      }
    },
    "package": {
      "repository": "https://github.com/entropy-tamer/mappy.git",
      "homepage": "https://github.com/entropy-tamer/mappy"
    }
  }
}
