[package]
name = "mappy-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core maplet data structure implementation"
readme = "../README.md"
keywords = ["data-structures", "filters", "approximate", "space-efficient", "maplets"]
categories = ["data-structures", "algorithms"]

[features]
default = ["quotient-filter"]
quotient-filter = []

[dependencies]
# Workspace dependencies
ahash.workspace = true
bitvec.workspace = true
twox-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
anyhow.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
rayon.workspace = true
tracing.workspace = true

# Additional dependencies
num-traits = "0.2.19"
smallvec = "1.15.1"
bytemuck = "1.24.0"

# Async runtime
tokio.workspace = true
async-trait.workspace = true

# Storage backends
dashmap = "6.1.0"
sled = "0.34.7"
tempfile = "3.23.0"

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
quickcheck.workspace = true
tempfile = "3.23.0"
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
redis = { version = "0.32.7", features = ["tokio-comp", "aio"] }

[[bench]]
name = "comparison"
harness = false

[[bench]]
name = "maplet_vs_std"
harness = false

[[bench]]
name = "storage_benchmarks"
harness = false

[[bench]]
name = "redis_comparison"
harness = false

[[bench]]
name = "basic_quotient_filter_benchmarks"
harness = false


# Linting configuration
[lints.clippy]
pedantic = "warn"
nursery = "warn"
cargo = "warn"
all = "warn"
